"""empty message

Revision ID: 64f256fdbd90
Revises: 5fc098ebdd3a
Create Date: 2023-10-28 11:45:22.940718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f256fdbd90'
down_revision = '5fc098ebdd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint('fk_friendships_receiver_id_accounts', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_friendships_receiver_id_accounts', 'accounts', ['receiver_id'], ['id'])

    # ### end Alembic commands ###
