"""creates models

Revision ID: 8acc18fb050f
Revises: d0cf860f6ea8
Create Date: 2023-10-28 11:38:03.865877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8acc18fb050f'
down_revision = 'd0cf860f6ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['accounts.id'], name=op.f('fk_friendships_receiver_id_accounts')),
    sa.ForeignKeyConstraint(['sender_id'], ['accounts.id'], name=op.f('fk_friendships_sender_id_accounts')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    op.drop_table('messages')
    # ### end Alembic commands ###
